# You can access http://localhost:3000/api to see swagger documentation
POST http://localhost:3000/current-account/ HTTP/1.1
content-type: application/json

{
  "custumerId": 1,
  "initialCredit": 25.51
}

###
GET http://localhost:3000/current-account/basic-info/28
content-type: application/json
